routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ImageController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\PesertaController;
use App\Http\Controllers\SponsorController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\SubeventController;
use App\Http\Controllers\UserHomeController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\MaineventController;
use App\Http\Controllers\PesertaLoginController;
use App\Http\Controllers\PesertaRegisterController;
use App\Http\Controllers\PembayaranExportController;
use App\Http\Controllers\DashboardSubeventController;
use App\Http\Controllers\DashboardPembayaranController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [HomeController::class, 'home'])->name('home');
Route::get('/about', [HomeController::class, 'about'])->name('about');

Route::get('/our-sponsor', [SponsorController::class, 'index']);


// Peserta

Route::get('/home', [UserHomeController::class, 'index']); //Hanya Boleh setelah Login

Route::get('/regis-lfls', [UserHomeController::class, 'form']); //Hanya Boleh setelah Login
Route::post('/regis-lfls', [PesertaController::class, 'form']); //Hanya Boleh setelah Login

Route::get('/status', [UserHomeController::class, 'status']); //Hanya Boleh setelah Login

// REGISTRASI MAIN EVENT
Route::get('/regis-main', [UserHomeController::class, 'formMain']); //Hanya Boleh setelah Login
Route::post('/regis-main', [PesertaController::class, 'formMain']); //Hanya Boleh setelah Login

// LOGOUT
Route::post('/logout', [LoginController::class, 'logout']);
Route::post('/peserta-logout', [PesertaLoginController::class, 'logout']);

// PESERTA
Route::post('/peserta-login', [PesertaLoginController::class, 'authenticate']);
Route::post('/peserta-regis', [PesertaRegisterController::class, 'store']);

// Coba Tiket
Route::get('/tiket', function () {
    return view('peserta.tiket');
});
Route::get('/cetak-tiket/{id}/{nama}', [PesertaController::class, 'cetak_tiket']);



// ADMIN
Route::get('/login', [LoginController::class, 'index']);
Route::post('/login', [LoginController::class, 'authenticate']);

// ADMIN Registration
Route::get('/regis', [RegisterController::class, 'index']);
Route::post('/regis', [RegisterController::class, 'store']);

// Authenticated user only
Route::group(['middleware' => 'auth'], function() {

    //User with admin type
    Route::group(['middleware' => 'cektipe:admin'], function() {
        Route::get('/dashboard', [DashboardController::class, 'index']);
        Route::resource('/subevents', DashboardSubeventController::class);
        Route::resource('/mainevent_bayar', DashboardPembayaranController::class);
        Route::get('image/{pembayaran:bukti_bayar}', [ImageController::class, 'index']);
        Route::get('/exportspembayaran', [PembayaranExportController::class, 'pembayaranExport']);
    });

    Route::group(['middleware' => 'cektipe:peserta'], function() {
        Route::get('/home', [UserHomeController::class, 'index']);
    });

});

// Route::get('/subevent', function () {
//     return view('admin/sub_event');
// });

// Subevent

// Mainevent
Route::get('/mainevent', [MaineventController::class, 'index']);
Route::put('/mainevent/{id}', [PesertaController::class, 'editstatus']);

// Route::get('/mainevent_bayar', [DashboardPembayaranController::class, 'index']);

resources/views/admin/admin_footer.blade.php
            <!-- Footer -->
            <footer class="content-footer footer bg-footer-theme">
                <div class="container-xxl d-flex flex-wrap justify-content-between py-2 flex-md-row flex-column">
                  <div class="mb-2 mb-md-0">
                    ©
                    <script>
                      document.write(new Date().getFullYear());
                    </script>
                    , made with ❤️ by
                   TEDxUniversitasAirlangga’s
                  </div>
                </div>
              </footer>
              <!-- / Footer -->
  
              <div class="content-backdrop fade"></div>
            </div>
            <!-- Content wrapper -->
          </div>
          <!-- / Layout page -->
        </div>
  
        <!-- Overlay -->
        <div class="layout-overlay layout-menu-toggle"></div>
      </div>
      <!-- / Layout wrapper -->
  
      <div class="buy-now">
        {{-- <a
          href="https://themeselection.com/products/sneat-bootstrap-html-admin-template/"
          target="_blank"
          class="btn btn-danger btn-buy-now"
          >Upgrade to Pro</a
        > --}}
      </div>
  
      <!-- Core JS -->
      <!-- build:admin/dashboard/assets/vendor/js/core.js -->
      <script src="admin/dashboard/assets/vendor/libs/jquery/jquery.js"></script>
      <script src="admin/dashboard/assets/vendor/libs/popper/popper.js"></script>
      <script src="admin/dashboard/assets/vendor/js/bootstrap.js"></script>
      <script src="admin/dashboard/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>
  
      <script src="admin/dashboard/assets/vendor/js/menu.js"></script>
      <!-- endbuild -->
  
      <!-- Vendors JS -->
      <script src="admin/dashboard/assets/vendor/libs/apex-charts/apexcharts.js"></script>
  
      <!-- Main JS -->
      <script src="admin/dashboard/assets/js/main.js"></script>
  
      <!-- Page JS -->
      <script src="admin/dashboard/assets/js/dashboards-analytics.js"></script>
  
      <!-- Place this tag in your head or just before your close body tag. -->
      <script async defer src="https://buttons.github.io/buttons.js"></script>

      <!-- AJAX -->
      <script src="{{ asset('js/admin/ajax.js') }}"></script>

    </body>
  </html>
  

resources/views/admin/admin_header.blade.php
<!DOCTYPE html>

<html
  lang="en"
  class="light-style layout-menu-fixed"
  dir="ltr"
  data-theme="theme-default"
  data-assets-path="admin/dashboard/assets/"
  data-template="vertical-menu-template-free"
>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0"
    />

    <title>ADMIN TedxUA 2022</title>

    <meta name="description" content="" />
    
    <!-- AJAX Setup CSRF -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="admin/dashboard/assets/img/favicon/favicon.ico" />

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
      rel="stylesheet"
    />

    <!-- Icons. Uncomment required icon fonts -->
    <link rel="stylesheet" href="admin/dashboard/assets/vendor/fonts/boxicons.css" />

    <!-- Core CSS -->
    <link rel="stylesheet" href="admin/dashboard/assets/vendor/css/core.css" class="template-customizer-core-css" />
    <link rel="stylesheet" href="admin/dashboard/assets/vendor/css/theme-default.css" class="template-customizer-theme-css" />
    <link rel="stylesheet" href="admin/dashboard/assets/css/demo.css" />

    <!-- Vendors CSS -->
    <link rel="stylesheet" href="admin/dashboard/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css" />

    <link rel="stylesheet" href="admin/dashboard/assets/vendor/libs/apex-charts/apex-charts.css" />

    <!-- Page CSS -->

    <!-- Helpers -->
    <script src="admin/dashboard/assets/vendor/js/helpers.js"></script>

    <!--! Template customizer & Theme config files MUST be included after core stylesheets and helpers.js in the <head> section -->
    <!--? Config:  Mandatory theme config file contain global vars & default theme options, Set your preferred theme option in this file.  -->
    <script src="admin/dashboard/assets/js/config.js"></script>
  </head>

  <body>
    <!-- Layout wrapper -->
    <div class="layout-wrapper layout-content-navbar">
      <div class="layout-container">
        <!-- Menu -->

        <aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
          <div class="app-brand demo">
            <a href="index.html" class="app-brand-link">
              <span class="app-brand-logo demo">
                <svg
                  width="25"
                  viewBox="0 0 25 42"
                  version="1.1"
                  xmlns="http://www.w3.org/2000/svg"
                  xmlns:xlink="http://www.w3.org/1999/xlink"
                >
                  <defs>
                    <path
                      d="M13.7918663,0.358365126 L3.39788168,7.44174259 C0.566865006,9.69408886 -0.379795268,12.4788597 0.557900856,15.7960551 C0.68998853,16.2305145 1.09562888,17.7872135 3.12357076,19.2293357 C3.8146334,19.7207684 5.32369333,20.3834223 7.65075054,21.2172976 L7.59773219,21.2525164 L2.63468769,24.5493413 C0.445452254,26.3002124 0.0884951797,28.5083815 1.56381646,31.1738486 C2.83770406,32.8170431 5.20850219,33.2640127 7.09180128,32.5391577 C8.347334,32.0559211 11.4559176,30.0011079 16.4175519,26.3747182 C18.0338572,24.4997857 18.6973423,22.4544883 18.4080071,20.2388261 C17.963753,17.5346866 16.1776345,15.5799961 13.0496516,14.3747546 L10.9194936,13.4715819 L18.6192054,7.984237 L13.7918663,0.358365126 Z"
                      id="path-1"
                    ></path>
                    <path
                      d="M5.47320593,6.00457225 C4.05321814,8.216144 4.36334763,10.0722806 6.40359441,11.5729822 C8.61520715,12.571656 10.0999176,13.2171421 10.8577257,13.5094407 L15.5088241,14.433041 L18.6192054,7.984237 C15.5364148,3.11535317 13.9273018,0.573395879 13.7918663,0.358365126 C13.5790555,0.511491653 10.8061687,2.3935607 5.47320593,6.00457225 Z"
                      id="path-3"
                    ></path>
                    <path
                      d="M7.50063644,21.2294429 L12.3234468,23.3159332 C14.1688022,24.7579751 14.397098,26.4880487 13.008334,28.506154 C11.6195701,30.5242593 10.3099883,31.790241 9.07958868,32.3040991 C5.78142938,33.4346997 4.13234973,34 4.13234973,34 C4.13234973,34 2.75489982,33.0538207 2.37032616e-14,31.1614621 C-0.55822714,27.8186216 -0.55822714,26.0572515 -4.05231404e-15,25.8773518 C0.83734071,25.6075023 2.77988457,22.8248993 3.3049379,22.52991 C3.65497346,22.3332504 5.05353963,21.8997614 7.50063644,21.2294429 Z"
                      id="path-4"
                    ></path>
                    <path
                      d="M20.6,7.13333333 L25.6,13.8 C26.2627417,14.6836556 26.0836556,15.9372583 25.2,16.6 C24.8538077,16.8596443 24.4327404,17 24,17 L14,17 C12.8954305,17 12,16.1045695 12,15 C12,14.5672596 12.1403557,14.1461923 12.4,13.8 L17.4,7.13333333 C18.0627417,6.24967773 19.3163444,6.07059163 20.2,6.73333333 C20.3516113,6.84704183 20.4862915,6.981722 20.6,7.13333333 Z"
                      id="path-5"
                    ></path>
                  </defs>
                  <g id="g-app-brand" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                    <g id="Brand-Logo" transform="translate(-27.000000, -15.000000)">
                      <g id="Icon" transform="translate(27.000000, 15.000000)">
                        <g id="Mask" transform="translate(0.000000, 8.000000)">
                          <mask id="mask-2" fill="white">
                            <use xlink:href="#path-1"></use>
                          </mask>
                          <use fill="#696cff" xlink:href="#path-1"></use>
                          <g id="Path-3" mask="url(#mask-2)">
                            <use fill="#696cff" xlink:href="#path-3"></use>
                            <use fill-opacity="0.2" fill="#FFFFFF" xlink:href="#path-3"></use>
                          </g>
                          <g id="Path-4" mask="url(#mask-2)">
                            <use fill="#696cff" xlink:href="#path-4"></use>
                            <use fill-opacity="0.2" fill="#FFFFFF" xlink:href="#path-4"></use>
                          </g>
                        </g>
                        <g
                          id="Triangle"
                          transform="translate(19.000000, 11.000000) rotate(-300.000000) translate(-19.000000, -11.000000) "
                        >
                          <use fill="#696cff" xlink:href="#path-5"></use>
                          <use fill-opacity="0.2" fill="#FFFFFF" xlink:href="#path-5"></use>
                        </g>
                      </g>
                    </g>
                  </g>
                </svg>
              </span>
              <span class="app-brand-text demo menu-text fw-bolder ms-2">TedXUA</span>
            </a>

            <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
              <i class="bx bx-chevron-left bx-sm align-middle"></i>
            </a>
          </div>

          <div class="menu-inner-shadow"></div>

          <ul class="menu-inner py-1">
            <!-- Dashboard -->
            <li class="menu-item active">
              <a href="/dashboard" class="menu-link">
                <i class="menu-icon tf-icons bx bx-home-circle"></i>
                <div data-i18n="Analytics">Dashboard</div>
              </a>
            </li>

            <!-- Layouts -->


            <li class="menu-header small text-uppercase">
              <span class="menu-header-text">Menu</span>
            </li>

            <!-- Cards -->
            <li class="menu-item">
              <a href="/subevents" class="menu-link">
                <i class="menu-icon tf-icons bx bx-collection"></i>
                <div data-i18n="Basic">Sub Event</div>
              </a>
            </li>
            <li class="menu-item">
                <a href="javascript:void(0);" class="menu-link menu-toggle">
                  <i class="menu-icon tf-icons bx bx-dock-top"></i>
                  <div data-i18n="Account Settings">Main event</div>
                </a>
                <ul class="menu-sub">
                  <li class="menu-item">
                    <a href="/mainevent" class="menu-link">
                      <div data-i18n="Account">Pendaftaran</div>
                    </a>
                  </li>
                  <li class="menu-item">
                    <a href="/mainevent_bayar" class="menu-link">
                      <div data-i18n="Notifications">pembayaran</div>
                    </a>
                  </li>
                </ul>
              </li>

          </ul>
        </aside>
        <!-- / Menu -->

        <!-- Layout container -->
        <div class="layout-page">
          <!-- Navbar -->

          <nav
            class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme"
            id="layout-navbar"
          >
            <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
              <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
                <i class="bx bx-menu bx-sm"></i>
              </a>
            </div>

            <div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">
              <!-- Search -->
              <div class="navbar-nav align-items-center">
                <div class="nav-item d-flex align-items-center">
                  <i class="bx bx-search fs-4 lh-0"></i>
                  <input
                    type="text"
                    class="form-control border-0 shadow-none"
                    placeholder="Search..."
                    aria-label="Search..."
                  />
                </div>
              </div>
              <!-- /Search -->

              <ul class="navbar-nav flex-row align-items-center ms-auto">
                <!-- Place this tag where you want the button to render. -->
                <li class="nav-item lh-1 me-3">
                  <a
                    class="github-button"
                    href="https://github.com/themeselection/sneat-html-admin-template-free"
                    data-icon="octicon-star"
                    data-size="large"
                    data-show-count="true"
                    aria-label="Star themeselection/sneat-html-admin-template-free on GitHub"
                    >Star</a
                  >
                </li>

                <!-- User -->
                <li class="nav-item navbar-dropdown dropdown-user dropdown">
                  <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
                    <div class="avatar avatar-online">
                      <img src="admin/dashboard/assets/img/avatars/1.png" alt class="w-px-40 h-auto rounded-circle" />
                    </div>
                  </a>
                  <ul class="dropdown-menu dropdown-menu-end">
                    <li>
                      <a class="dropdown-item" href="#">
                        <div class="d-flex">
                          <div class="flex-shrink-0 me-3">
                            <div class="avatar avatar-online">
                              <img src="admin/dashboard/assets/img/avatars/1.png" alt class="w-px-40 h-auto rounded-circle" />
                            </div>
                          </div>
                          <div class="flex-grow-1">
                            <span class="fw-semibold d-block">John Doe</span>
                            <small class="text-muted">Admin</small>
                          </div>
                        </div>
                      </a>
                    </li>
                    <li>
                      <div class="dropdown-divider"></div>
                    </li>
                    <li>
                      <a class="dropdown-item" href="#">
                        <i class="bx bx-user me-2"></i>
                        <span class="align-middle">My Profile</span>
                      </a>
                    </li>
                    <li>
                      <a class="dropdown-item" href="#">
                        <i class="bx bx-cog me-2"></i>
                        <span class="align-middle">Settings</span>
                      </a>
                    </li>
                    <li>
                      <a class="dropdown-item" href="#">
                        <span class="d-flex align-items-center align-middle">
                          <i class="flex-shrink-0 bx bx-credit-card me-2"></i>
                          <span class="flex-grow-1 align-middle">Billing</span>
                          <span class="flex-shrink-0 badge badge-center rounded-pill bg-danger w-px-20 h-px-20">4</span>
                        </span>
                      </a>
                    </li>
                    <li>
                      <div class="dropdown-divider"></div>
                    </li>
                    <li>
                      {{-- <a class="dropdown-item" href="auth-login-basic.html"> --}}
                        <i class="bx bx-power-off me-2"></i>
                          <form action="/logout" method="POST">
                            @csrf
                            <button class="align-middle"><span class="align-middle">Log Out</span></button>
                        </form>

                      {{-- </a> --}}
                    </li>
                  </ul>
                </li>
                <!--/ User -->
              </ul>
            </div>
          </nav>

          <!-- / Navbar -->

resources/views/admin/bukti_pembayaran.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Bukti Pembayaran</title>
</head>
<body>
    <img src="{{ asset('bukti_bayar/' . $file_name) }}" alt="">
</body>
</html>

resources/views/admin/dashboard.blade.php
@include('admin/admin_header')
          <!-- Content wrapper -->
          <div class="content-wrapper">
            <!-- Content -->

            <div class="container-xxl flex-grow-1 container-p-y">
              <div class="row">

                <div class="col-lg-12 col-md-4 order-1">
                  <div class="row">
                    <div class="col-lg-6 col-md-12 col-6 mb-4">
                      <div class="card">
                        <div class="card-body">
                          <div class="card-title d-flex align-items-start justify-content-between">
                            <div class="avatar flex-shrink-0">
                              <img
                                src="admin/dashboard/assets/img/icons/unicons/chart-success.png"
                                alt="chart success"
                                class="rounded"
                              />
                            </div>
                            <div class="dropdown">
                              <button
                                class="btn p-0"
                                type="button"
                                id="cardOpt3"
                                data-bs-toggle="dropdown"
                                aria-haspopup="true"
                                aria-expanded="false"
                              >
                                <i class="bx bx-dots-vertical-rounded"></i>
                              </button>
                              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="cardOpt3">
                                <a class="dropdown-item" href="javascript:void(0);">View More</a>
                                <a class="dropdown-item" href="javascript:void(0);">Delete</a>
                              </div>
                            </div>
                          </div>
                          <span class="fw-semibold d-block mb-1">Pendaftar Sub Event</span>
                          <h3 class="card-title mb-2">{{ $jml_peserta_subevent }}</h3>
                          {{-- <small class="text-success fw-semibold"><i class="bx bx-up-arrow-alt"></i> +72.80%</small> --}}
                        </div>
                      </div>
                    </div>
                    <div class="col-lg-6 col-md-12 col-6 mb-4">
                      <div class="card">
                        <div class="card-body">
                          <div class="card-title d-flex align-items-start justify-content-between">
                            <div class="avatar flex-shrink-0">
                              <img
                                src="admin/dashboard/assets/img/icons/unicons/wallet-info.png"
                                alt="Credit Card"
                                class="rounded"
                              />
                            </div>
                            <div class="dropdown">
                              <button
                                class="btn p-0"
                                type="button"
                                id="cardOpt6"
                                data-bs-toggle="dropdown"
                                aria-haspopup="true"
                                aria-expanded="false"
                              >
                                <i class="bx bx-dots-vertical-rounded"></i>
                              </button>
                              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="cardOpt6">
                                <a class="dropdown-item" href="javascript:void(0);">View More</a>
                                <a class="dropdown-item" href="javascript:void(0);">Delete</a>
                              </div>
                            </div>
                          </div>
                          <span>Pendaftaran Main Event</span>
                          <h3 class="card-title text-nowrap mb-1">{{ $jml_peserta_mainevent }}</h3>
                          {{-- <small class="text-success fw-semibold"><i class="bx bx-up-arrow-alt"></i> +28.42%</small> --}}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>

              </div>

            </div>
            <!-- / Content -->


            
            <!-- / Content -->
@include('admin/admin_footer')

resources/views/admin/sub_event.blade.php
@include('admin/admin_header')

<div class="content-wrapper">
    <!-- Content -->
    <div class="container-xxl flex-grow-1 container-p-y">
        <div class="row">
            <!-- Striped Rows -->
              <div class="card">
                <h5 class="card-header">Pendaftaran Sub Event</h5>
                <div class="table-responsive text-nowrap">
                  <table class="table table-striped">
                    <thead>
                      <tr>
                        <th>Nama</th>
                        <th>NIM</th>
                        <th>Fakultas</th>
                        <th>Angkatan</th>
                        <th>Email</th>
                        <th>Tanggal Pendaftaran</th>
                        <th>Status</th>
                        <th>Detail</th>
                      </tr>
                    </thead>
                    <tbody class="table-border-bottom-0">
                      @foreach ($pendaftarans as $pendaftaran)
                        <tr>
                          <td> <strong>{{$pendaftaran->peserta->nama}}</strong></td>
                          <td>{{$pendaftaran->peserta->nim}}</td>
                          <td>{{$pendaftaran->peserta->fakultas}}</td>
                          <td>{{$pendaftaran->peserta->angkatan}}</td>
                          <td>{{$pendaftaran->peserta->user->email}}</td>
                          <td>{{ date('d F Y', strtotime($pendaftaran->peserta->pendaftaran->created_at)); }}</td>

                          <td>
                            <select class="btn rounded-pill btn-outline-warning status" data-id="{{ $pendaftaran->peserta->id }}" aria-label="Default select example">
                              <option value="0" {{ ($pendaftaran->status == 0) ? 'selected' : '' }}>Unverified</option>
                              <option value="1" {{ ($pendaftaran->status == 1) ? 'selected' : '' }}>Verified</option>
                              <option value="2" {{ ($pendaftaran->status == 2) ? 'selected' : '' }}>Berkas Kurang / Salah</option>
                            </select>
                          </td>
                          <td>
                              <button type="button" id="show-subevent" class="btn rounded-pill btn-outline-info" data-bs-toggle="modal"
                              data-bs-target="#showModal" data-url="{{ route('subevents.show', $pendaftaran->peserta->id) }}">Info</button>
                          </td>
                        </tr>
                      @endforeach



                    </tbody>
                  </table>
                </div>
              </div>
              <!--/ Striped Rows -->
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="showModal" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
      <div class="modal-header">
          <h5 class="modal-title" id="modalCenterTitle">Pendaftaran Sub Event</h5>
          <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
          ></button>
      </div>
      <div class="modal-body">
          <div class="row">
              <div class="col mb-3">
                  <label for="peserta-nama" class="form-label">Nama</label>
                  <input type="text" id="peserta-nama" class="form-control" value="" readonly/>
              </div>
          </div>
          <div class="row g-2 mb-1">
              <div class="col mb-0">
                  <label for="peserta-fakultas" class="form-label">Fakultas</label>
                  <input type="text" id="peserta-fakultas" value="" class="form-control" readonly/>
              </div>
              <div class="col mb-0">
                  <label for="peserta-angkatan" class="form-label">Angkatan</label>
                  <input type="text" id="peserta-angkatan" value="" class="form-control" readonly/>
              </div>
          </div>
          <div class="row">
            <div class="col mb-3">
                <label for="peserta-nama" class="form-label">Kontak</label>
                <input type="text" id="peserta-kontak" class="form-control" value="" readonly/>
            </div>
        </div>
          <div class="row">
            <div class="col mb-3">
                <label for="peserta-nama" class="form-label">Alamat</label>
                <input type="text" id="peserta-alamat" class="form-control" value="" readonly/>
            </div>
        </div>
        <div class="row">
          <div class="col mb-3">
              <label for="peserta-nama" class="form-label">Instagrm</label>
              <input type="text" id="peserta-instagram" class="form-control" value="" readonly/>
          </div>
      </div>
        <div class="row">
          <div class="col mb-3">
              <label for="peserta-nama" class="form-label">Drive</label>
              <input type="text" id="peserta-drive" class="form-control" value="" readonly/>
          </div>
      </div>
      </div>
      <div class="modal-footer">
          <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">
          Close
          </button>
      </div>
      </div>
  </div>
</div>


@include('admin/admin_footer')